### ISSUE TITLE
React state updated when component unmounted

### ISSUE THREAD

**Issue by bitburnerz** [GreenStage/react-central-state#1]
I'm updating the central state each time a new websocket message is received. This is happening outside of any React components. The way I do this is by creating a new handler and using setCentralState(). Now, when I switch tabs in the application window, components for that tab are unmounted, yet it seems react-central-state is still trying to update them as new websocket messages are coming in. I get the error "Warning: Can't perform a React state update on this unmounted component. This is a non-op, but it indicates a memory leak...". Shouldn't react-central-state handle this for me automatically?

**Comment by GreenStage** [comment]
I think i was able to replicate this issue and fix it in f3105bf0101dd8877ed129a045ee7ee7d8d04f48
Did it fix your problem?

**Comment by bitburnerz** [comment]
Works like a charm. Thank you!
